### ISSUE TITLE
Migrate download links off of Google Code, which is soon to be discontinued

### ISSUE THREAD

**Issue by alebcay** [caskroom/homebrew-cask#10461]
As mentioned [here](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html), Google Code will be going into read-only mode later this year in August, and complete discontinuation is scheduled for the end of 2016.

While these dates are a long ways off, it means that sources on Google Code soon may become outdated as the projects move off of Google Code and find hosting elsewhere.

This is a list of Casks in the main repository that currently point to Google Code (`homepage` or `url`):
- [ ] [`appmenuboy`](../tree/master/Casks/appmenuboy.rb)
- [ ] [`cert-quicklook`](../tree/master/Casks/cert-quicklook.rb)
- [x] [`cantata`](../tree/master/Casks/cantata.rb)
- [ ] [`colors`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/colors.rb)
- [x] [`comictagger`](../tree/master/Casks/comictagger.rb)
- [ ] [`cronnix`](../tree/master/Casks/cronnix.rb)
- [x] [`dictunifier`](../tree/master/Casks/dictunifier.rb)
- [x] [`dukto`](../tree/master/Casks/dukto.rb)
- [ ] [`duplicati`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/duplicati.rb)
- [x] [`electric-sheep`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/electric-sheep.rb)
- [ ] [`epub-to-pdf`](../tree/master/Casks/epub-to-pdf.rb)
- [ ] [`fluke`](../tree/master/Casks/fluke.rb)
- [ ] [`fotowall`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/fotowall.rb)
- [x] [`ganttproject`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/ganttproject.rb)
- [x] [`gargoyle`](../tree/master/Casks/gargoyle.rb)
- [ ] [`ichm`](../tree/master/Casks/ichm.rb)
- [x] [`klystrack`](../tree/master/Casks/klystrack.rb)
- [x] [`macvim`](../tree/master/Casks/macvim.rb)
- [ ] [`maratis`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/maratis.rb)
- [ ] [`namebench`](../tree/master/Casks/namebench.rb)
- [ ] [`nethackcocoa`](../tree/master/Casks/nethackcocoa.rb)
- [ ] [`nocturne`](../tree/master/Casks/nocturne.rb)
- [x] [`nosleep`](../tree/master/Casks/nosleep.rb)
- [ ] [`pencil`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/pencil.rb)
- [x] [`port-map`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/port-map.rb)
- [ ] [`proximity`](../tree/master/Casks/proximity.rb)
- [ ] [`quick-search-box`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/quick-search-box.rb)
- [ ] [`quicklook-csv`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/quicklook-csv.rb)
- [ ] [`quicklook-pfm`](../tree/master/Casks/quicklook-pfm.rb)
- [ ] [`raptor`](../tree/master/Casks/raptor.rb)
- [ ] [`secrets`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/secrets.rb)
- [x] [`sequel-pro`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/sequel-pro.rb)
- [ ] [`skreenics`](../tree/master/Casks/skreenics.rb)
- [x] [`soundflower`](../tree/master/Casks/soundflower.rb)
- [ ] [`spek`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/spek.rb)
- [x] [`splitshow`](../tree/master/Casks/splitshow.rb)
- [x] [`spyder`](../tree/master/Casks/spyder.rb)
- [x] [`squirrel`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/squirrel.rb)
- [x] [`subler`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/subler.rb)
- [ ] [`svnx`](../tree/master/Casks/svnx.rb)
- [ ] [`textroom`](../tree/master/Casks/textroom.rb)
- [x] [`the-unarchiver`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/the-unarchiver.rb)
- [ ] [`time-tracker`](../tree/master/Casks/time-tracker.rb)
- [x] [`transmission-remote-gui`](../tree/master/Casks/transmission-remote-gui.rb)
- [x] [`tomighty`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/tomighty.rb)
- [x] [`tunnelblick`](../tree/master/Casks/tunnelblick.rb)
- [ ] [`welly`](../tree/master/Casks/welly.rb)
- [x] [`wiztoolsorg-restclient`](../tree/master/Casks/wiztoolsorg-restclient.rb)
- [ ] [`wjoy`](../tree/master/Casks/wjoy.rb)
- [x] [`xld`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/xld.rb)

**Comment by anantshri** [comment]
my #2cents of help here.


raptor-chess-interface : https://github.com/ddugovic/raptor-chess-interface

arora : https://github.com/Arora/arora

However i was not able to find proper replacement sources hence no pull request. 

will add more and if i find a release link will add details in correct place.

**Comment by leipert** [comment]
It seems like you missed some casks, as the following contain urls with `subdomain.googlecode.com` and are not in the list above.

- [ ] [`colors`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/colors.rb)
- [ ] [`duplicati`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/duplicati.rb)
- [ ] [`electric-sheep`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/electric-sheep.rb)
- [ ] [`fotowall`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/fotowall.rb)
- [ ] [`ganttproject`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/ganttproject.rb)
- [ ] [`ichm`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/ichm.rb)
- [ ] [`maratis`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/maratis.rb)
- [ ] [`pencil`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/pencil.rb)
- [ ] [`port-map`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/port-map.rb)
- [ ] [`quick-search-box`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/quick-search-box.rb)
- [ ] [`quicklook-csv`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/quicklook-csv.rb)
- [ ] [`secrets`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/secrets.rb)
- [ ] [`sequel-pro`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/sequel-pro.rb)
- [ ] [`spek`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/spek.rb)
- [ ] [`squirrel`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/squirrel.rb)
- [ ] [`subler`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/subler.rb)
- [ ] [`the-unarchiver`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/the-unarchiver.rb)
- [ ] [`tomighty`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/tomighty.rb)
- [ ] [`xld`](https://github.com/caskroom/homebrew-cask/tree/master/Casks/xld.rb)

**Comment by vitorgalvao** [comment]
Thank you for the list, @leipert. Moved to the top post.

**Comment by leipert** [comment]
What happens, once they shutdown and not every project is transferred by their owners.
Are the casks simply discarded or would you try to find a mirror for them?

**Comment by vitorgalvao** [comment]
They’ll be discarded. Many of those are likely discontinued (like `quick-search-box`), anyway, and we only accept official links, so no mirrors.

It’s completely outside the scope of homebrew-cask to mirror apps. We’re not an archive, and have neither the money nor the resources. If someone else is interested in reviving those products, they’re free to submit them to us, but otherwise it’d be an absolute waste of time and resources for us to do it.

**Comment by leipert** [comment]
Okay, good to know. A lot of them seem to be for older OSX versions anyway.

**Comment by vitorgalvao** [comment]
Yep. Removing apps is always good. Many times we have a one-time submission for obscure apps and the cask is never touched again. Having less of them means we can be more effective in keeping everything clean and correct.

**Comment by leipert** [comment]
Did you ever think about stats, which apps get installed (on a voluntary basis), so that unused casks could be removed automically?

**Comment by vitorgalvao** [comment]
The idea has been asked and discussed a few times, but always refused. I’m adamant on “no”, for privacy reasons. And if we ask users first (definitely the only correct way to go about collecting this data), then the numbers we get aren’t real anyway, and we can’t trust them.

There’s [a long issue on this](https://github.com/caskroom/homebrew-cask/issues/4323), but I don’t necessarily recommend you read it. It’s long and frustrating, with the user arguing for it having very broken english and ignoring (or not understanding) the counter points, leading to a lot of the same arguments being made repeatedly, so it’s not a pleasant read.

**Comment by leipert** [comment]
My oh my. I flew over the issue :dancer:
Well shame, that casks are not retrieved with an api, otherwise the stats would be there automagically. I see the privacy arguments and I wouldn't recommend a curl with an unique identifier per machine.
The funny thing is, almost every other package service like npm or apt in debian provides the possibility of collecting stats.

Knowing that you are a "no"-advocate, you could get useful results from just a few participants.
You could implement the following workflow (numbers are arbitrary and exchangeable):

1. Every cask has a "last time installed" timestamp
2. If a cask has not been installed for six months, it get's a deprecated flag
    3. If a user, whom allows sending data, installs a cask with a timestamp older than two weeks :arrow_forward: Update timestamp (and remove deprecated flag)
    4. If a cask with deprecated flag is updated :arrow_forward: remove flag
    5. If a cask with deprecated flag is installed by a user, whom does not allow sending data :arrow_forward:  show warning, that this cask is deprecated and show him how to remove the flag
6. Each cask that was deprecated for more than two months get's removed

The sending of data would be opt-in and not tied to an account/mac. Even if you opt-in, you won't send data every time. If you are interested in a proof of concept, I would be happy to provide an api.

**Comment by vitorgalvao** [comment]
`npm` and `apt` have control over the packages themselves, though, while we’re just dumb links to outside sources. Not saying that invalidates privacy concerns or anything, but when you have full control over your system, new things are allowed. We’ll never be able to do that, because unlike most package managers we have a huge amount of commercial software, which brings licensing implications.

Also keep in mind I don’t necessarily think we should be removing casks *just* because they’re unused. It has value that a new user can install homebrew-cask and find the obscure software they use is present. I like when we have less of them to worry about, yes, but removing them *just* because they haven’t been installed in a while isn’t a good metric. Typically you install apps once; not installing them again does not mean you don’t use it.

Point **2.iii** is also not something I’d be happy with. As @alebcay [said](https://github.com/caskroom/homebrew-cask/issues/4323#issuecomment-42784432) (second paragraph):

> Homebrew Cask (…) aims to be automated. That means as little interactivity as possible (e.g. yes/no prompts, etc.). Asking (…) is therefore not an option.

Anything that gives the user more work should be carefully weighted, and that feels like a punishment (in a light sense, being extra work) for not compromising your privacy (allowing data collection) and to me, the reverse should be true: be privacy conscious, and be rewarded (or at the very least as well served as those who are not).

**Comment by leipert** [comment]
Well that makes sense :) It's always a balancing act. Thanks for your explanation.

**Comment by vitorgalvao** [comment]
Closing this issue (migration) in favour of https://github.com/caskroom/homebrew-cask/issues/17075 (deletion).
