### ISSUE TITLE
`brew cask list` is broken

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#14058]
It likely requires a big restructuring. Currently some of its problems are:
- [x] [#2063: `brew cask list` should check arguments individually](https://github.com/caskroom/homebrew-cask/issues/2063).
- [x] [#2988: Uninstall cask report the cask is not installed while it is](https://github.com/caskroom/homebrew-cask/issues/2988).
- [ ] [#13525: `brew cask list` in a dir containing installed cask file(s) results in file does not exist error](https://github.com/caskroom/homebrew-cask/issues/13525).
- [x] [#18291: `brew cask list --versions` should list all versions of installed casks](https://github.com/caskroom/homebrew-cask/issues/18291)

@caskroom/maintainers should feel free to expand the list (and close the respective issues) so we can concentrate on a single one. Checkboxes should be ticked as things are solved.

**Comment by mAAdhaTTah** [comment]
I'm getting an error when running `brew cask list` as well:

> ○ → brew cask list
> Error: Cask 'onyx' definition is invalid: invalid 'depends_on :macos' value: ":el_capitan"

It doesn't look related to the two issues linked.

**Comment by vitorgalvao** [comment]
@mAAdhaTTah Very likely, you’re using an old version of homebrew-cask. `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`.

**Comment by vitorgalvao** [comment]
@mAAdhaTTah Since it is actually unrelated, I’l delete your comment and mine. Don’t want to pollute the issue.

**Comment by RandomDSdevel** [comment]
@reitermarkus:  You forgot to tick the third of the four checkboxes in the list of to-do items @vitorgalvao put in this issue's initial description (I checked, and #13525 _has_ been closed.)

**Comment by reitermarkus** [comment]
@RandomDSdevel, I could never actually reproduce the third issue, that's why I left it unchecked.

**Comment by vitorgalvao** [comment]
> (I checked, and #13525 has been closed.)

Yes, but it was closed because it was [superseded by this issue](https://github.com/caskroom/homebrew-cask/issues/13525#issuecomment-144016441), not because it was solved.

**Comment by RandomDSdevel** [comment]
@reitermarkus:  Ah, makes sense.  

<hr />

@vitorgalvao:  Ahck, how could I have overlooked that comment?!  In that case, you can just ignore my babbling and move on with other things.  (😆.)
