### ISSUE TITLE
Change `appcast` `:sha256` to `:checkpoint`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16949]
Refs https://github.com/caskroom/homebrew-cask/pull/16948. If agreed upon, steps:

- [x] Deprecate `:sha256` in `appcast`. (#16951)
- [x] Add `:checkpoint` (or other name) to `appcast`. (#16951)
- [x] Change all casks in main repo to use `:checkpoint`. (#16951)
- [x] Change all casks in versions repo to use `:checkpoint`. (https://github.com/caskroom/homebrew-versions/pull/1574)
- [ ] Add [sourceforge `appcast`s](https://github.com/caskroom/homebrew-cask/issues/16685).
- [x] Update documentation. (#17036)
- [x] Update details in #16689.
- [x] Update `cask-repair`. (https://github.com/vitorgalvao/tiny-scripts/commit/30c314d3c521ab7a77754ccc33b4f543d1f15bce)
- [x] Update `find_sparkle_appcast`. (#16974)

---

Discussed names:

+ `:checkpoint`
+ ~~`:control`~~
+ ~~`:value`~~
+ ~~`:version`~~
+ ~~`:update`~~
+ ~~`:identifier`~~
+ ~~`:update_id`~~
+ ~~`:id`~~

**Comment by adityadalal924** [comment]
The documentation is flexible - I also don't mind having a distinct stanza name. 

Not a huge fan of checkpoint, but maybe another maintainer will chime in with a better one.

Otherwise, +1 to the proposal - it seems like a lot of work up-front, but if it makes for an easier and more reliable update mechanism down the road, it's worth it.

**Comment by Amorymeltzer** [comment]
:+1: But I think a simple script to compute this value should be on that list

**Comment by vitorgalvao** [comment]
> But I think a simple script to compute this value should be on that list

`cask-repair` would be that script. Otherwise, if you want to do it manually, the instructions (where we explain what the value represents) would tell you to get it with `curl "{{appcast_url}}" | sed '/<pubDate>/d' | shasum --algorithm 256` (or to add `get_checkpoint() { curl "{{appcast_url}}" | sed '/<pubDate>/d' | shasum --algorithm 256`; }` to your shell’s startup files.

**Comment by vitorgalvao** [comment]
Added discussed names to the top post.

Personally, I’m more inclined for `:control` or `:checkpoint`. Even if not completely accurate, if we’re going for an identifier that represents a custom value that we’re the ones making up, might as well have a distinctive name, since that will both help to talk about it, and find it in code.

We need more opinions/ideas, here, just so we can move on and actually do it, as this small decision is holding up too much.

**Comment by adityadalal924** [comment]
Agreed on the unique name point - that's nice in documentation.

**Comment by jawshooah** [comment]
I thought I cared about the name, but as long as it's documented, it really doesn't matter to me. `:checkpoint` is fine.

**Comment by vitorgalvao** [comment]
I’m in the same “camp” of not really caring that much about what the final name ends up being (though I usually do, and have some I prefer) as long as well are fine with it.

@adityadalal924 [seems to be fine with `:checkpoint`](https://github.com/caskroom/homebrew-cask/issues/16689#issuecomment-171355826) as well, [considering the distinctive name argument](https://github.com/caskroom/homebrew-cask/issues/16949#issuecomment-171344365). What about you, @Amorymeltzer?

**Comment by Amorymeltzer** [comment]
Mmm, I like `:id`

**Comment by adityadalal924** [comment]
@vitorgalvao For updating documentation, is https://github.com/caskroom/homebrew-cask/issues/16690 something you are actively working on, or should this update be separate from that?

**Comment by vitorgalvao** [comment]
@adityadalal924 #16690 is about breaking it up, so for additions (this case) it should be separate.

**Comment by adidalal** [comment]
Closing, as adding sourceforge appcasts is already an issue (and isn't particularly relevant to the switch).
