### ISSUE TITLE
Remove Casks hosted on Google Code

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#17075]
As Google Code is [dead in 10 days](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html). List from https://github.com/caskroom/homebrew-cask/issues/17075#issuecomment-172418313.

Move to alehouse?
- [x]  [`cronnix.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cronnix.rb)
- [x]  [`epub-to-pdf.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/epub-to-pdf.rb)
- [x]  [`maratis.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/maratis.rb)
- [x]  [`pencil.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pencil.rb)
- [x]  [`quick-search-box.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/quick-search-box.rb)
- [x]  [`skreenics.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/skreenics.rb)

Asked to move hosting:
- [x]  [`duplicati.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/duplicati.rb) https://github.com/duplicati/duplicati/issues/1545
- [x]  [ `fotowall.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fotowall.rb) https://github.com/enricoros/fotowall/issues/9
- [x]  [ `nethackcocoa.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/nethackcocoa.rb) https://github.com/dirkz/NetHack-Cocoa/issues/1
- [x]  [ `proximity.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/proximity.rb) https://github.com/revned/proximity/issues/11
- [x]  [ `quicklook-pfm`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/quicklook-pfm.rb) https://github.com/lnxbil/quicklook-pfm/issues/3
- [x]  [ `spek.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/spek.rb) https://github.com/alexkay/spek/issues/88
- [x]  [ `time-tracker.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/time-tracker.rb) https://github.com/rburgst/time-tracker-mac/issues/147
- [x]  [ `welly.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/welly.rb) https://github.com/KOed/welly/issues/7
- [x]  [`wjoy.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/wjoy.rb) https://github.com/alxn1/wjoy/issues/88

Special case:
- [x]  [`namebench.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/namebench.rb) New development at [google/namebench](https://github.com/google/namebench), similar to formula [`namebench.rb`](https://github.com/Homebrew/homebrew/pull/21818) (cask includes gui, formula has cli only). No releases yet.

**Comment by vitorgalvao** [comment]
Pinging @alebcay as the keeper of alehouse.

I’d be happy to let those die, though. Clearly the interest isn’t there to fix them.

**Comment by alebcay** [comment]
Sure thing, I'll be happy to mirror them.

**Comment by vitorgalvao** [comment]
Updated top post with full list.

@alebcay You should feel free to let die whatever you want. Things like [`quick-search-box`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/quick-search-box.rb), for example, are guaranteed to never be worked on again.

**Comment by Zirro** [comment]
Looking at two of these that I use, qlcolorcode and quicklook-csv appear to have found [new](https://github.com/p2/quicklook-csv) [homes](https://github.com/n8gray/QLColorCode) on GitHub and can use a release from here.

I can submit pull requests with new urls for these casks in a few days.

**Comment by adidalal** [comment]
quicklook-csv: https://github.com/p2/quicklook-csv/releases

**Comment by tsparber** [comment]
So, finally I'm went through all files

Move to alehouse? (I have no other project found, but seems still working)
- [ ]  `cronnix.rb`
- [ ]  `epub-to-pdf.rb`
- [ ]  `maratis.rb`
- [ ]  `pencil.rb`
- [ ]  `quick-search-box.rb`
- [ ]  `screenics`

Asked to move hosting:
- [ ] `duplicati.rb` https://github.com/duplicati/duplicati/issues/1545
- [ ]  `fotowall.rb` https://github.com/enricoros/fotowall/issues/9
- [ ]  `nethackcocoa.rb` https://github.com/dirkz/NetHack-Cocoa/issues/1
- [ ]  `proximity.rb` https://github.com/revned/proximity/issues/11
- [ ]  `quicklook-pfm` https://github.com/lnxbil/quicklook-pfm/issues/3
- [ ]  `spek.rb` https://github.com/alexkay/spek/issues/88
- [ ]  `time-tracker.rb` https://github.com/rburgst/time-tracker-mac/issues/147
- [ ]  `welly.rb` https://github.com/KOed/welly/issues/7
- [ ]  `wjoy.rb` https://github.com/alxn1/wjoy/issues/88

Special case:
- [ ]  `namebench.rb` New development at [google/namebench](https://github.com/google/namebench), similar to formula [`namebench.rb`](https://github.com/Homebrew/homebrew/pull/21818) (cask includes gui, formula has cli only). No releases yet.

**Comment by vitorgalvao** [comment]
@tsparber Thank you. Updated top list. Removed `quick-search-box` because that’s more than dead.

**Comment by tsparber** [comment]
Was pointed to https://code.google.com/archive/d/code.google.com which contains everything, so no need for alehouse. Don't know googke will automatically redirect. We will see it after 25th.

**Comment by vitorgalvao** [comment]
I think that might be just the archive they’ll keep until the end of 2006. That should only serve complete tarballs of projects, so still no good for us.

**Comment by tsparber** [comment]
It is more than tarballs (https://code.google.com/archive/p/duplicati/downloads) basically a new readonly interface, labeled as "long term storage"

**Comment by vitorgalvao** [comment]
It’s fine in that case. We should label those as `discontinued`, though.

**Comment by tsparber** [comment]
- [ ]  [`maratis.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/maratis.rb) (Hompage links url to googlecode.com) (not dead, but [Maratis-4](https://github.com/anael-seghezzi/Maratis-4) has no releases)
- [ ]  [`pencil.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pencil.rb) (Hompage links url to googlecode.com) `discontinued`
- [ ]  [`duplicati.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/duplicati.rb) https://github.com/duplicati/duplicati/issues/1545 (WIP)
- [ ]  [ `fotowall.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/fotowall.rb) https://github.com/enricoros/fotowall/issues/9 (no response) (Hompage links url to googlecode.com) `discontinued`
- [ ]  [ `proximity.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/proximity.rb) https://github.com/revned/proximity/issues/11 (no response, url has [spaces -> maybe dead after shutdown / 404](https://code.google.com/p/support-tools/issues/detail?id=175)) `discontinued`

@vitorgalvao Is it ok to update the casks where the homepage points the url to googlecode.com to storage.google.com/archive? If not I will leave them until they return a 404 (if google does not redirect upon shutdown).

**Comment by vitorgalvao** [comment]
> Is it ok to update the casks where the homepage points the url to googlecode.com to storage.google.com/archive?

Yes.

**Comment by vitorgalvao** [comment]
Two more and we’re set. Tireless work, @tsparber, thank you.

**Comment by tsparber** [comment]
I like to finish things I start, but did not expect it to be so much work :smiley:
Sadly I don't know how to fix the remaining two :disappointed: ([bug](https://code.google.com/p/support-tools/issues/detail?id=175) on googles code archive)

**Comment by vitorgalvao** [comment]
Lets just remove those two.

+ `duplicati`: when it reaches `2.0` and there are binaries, someone will resubmit (if they don’t it’s because there isn’t any interest, which is also fine).
+ `proximity`: Was last touched over a year ago and looks pretty abandoned (issues are being apparently ignored).
