### ISSUE TITLE
Proposal: move caskroom/unofficial

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#18828]
Pinging @caskroom/maintainers. If there are no objections, will go ahead with it next Friday (February 19<sup>th</sup>, 2016).

I went through [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial) a few times lately, and can’t find a good reason to keep it. Apart from the funny notion we’re *officially* hosting a repo we call *unofficial*:

+ It has less than 40 casks.
+ [Many of them are potentially dangerous](https://github.com/caskroom/homebrew-unofficial/blob/master/README.md#homebrew-unofficial) (though in practice none should be).
+ Most are relatively obscure, and hence provide very little value ([which is important](https://github.com/caskroom/homebrew-versions#acceptable-casks)).
+ Many are *really specifically obscure* (specific forks with tiny modifications).
+ Many/most were introduced to serve a single user ([not something we adhere to](https://github.com/caskroom/homebrew-versions#acceptable-casks)).
+ Most, once added, are pretty much abandoned.

Finally, **all the casks in that repo are prime candidates for user taps**, and we should encourage that.

Things to be done:

- [x] Give [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial) to @alebcay.
- [x] Close https://github.com/caskroom/homebrew-cask/issues/8027.
- [x] Rectify documentation.
- [x] Update the outdated appcasts scripts.

**Comment by adidalal** [comment]
We could also drop them from alehouse, as they're probably useless there without a Cask there, anyway.

**Comment by vitorgalvao** [comment]
@adidalal Agreed, though for all intents and purposes that project is @alebcay’s, so alternatively he might even want to host the casks there.

**Comment by alebcay** [comment]
I would vouch for simply moving `caskroom/unofficial` to under my name and it would no longer need to be officially maintained by the Caskroom team.

You're still welcome to redirect custom/unofficial builds there if you want to.

**Comment by vitorgalvao** [comment]
@alebcay Fine by me. Lets still wait a few more days for further opinions.

**Comment by victorpopkov** [comment]
In my opinion, it would better to simply move as @alebcay suggested rather than deleting it. But I'm not against from completely removing it as I also don't see any good reasons why we should keep it.

**Comment by vitorgalvao** [comment]
@victorpopkov Sure, if @alebcay wants to maintain the repo, I see no reason to not move it instead of outright deleting it. Update title to reflect that.

**Comment by vitorgalvao** [comment]
Starting now the process.
![image](https://cloud.githubusercontent.com/assets/1699443/13178281/d16e0aa0-d715-11e5-9d16-3d19b258e4ba.png)

Will transfer it to myself and then to @alebcay.

**Comment by vitorgalvao** [comment]
Closing since process in underway.

**Comment by joshka** [comment]
For users with a previously tapped unofficial, `brew update` returns the following error:
```bash
$ brew update
remote: Repository not found.
fatal: repository 'https://github.com/caskroom/homebrew-unofficial/' not found
Error: Fetching /usr/local/Library/Taps/caskroom/homebrew-unofficial failed!
Updated 1 tap (caskroom/cask).
No changes to formulae.
```
Additionally, there doesn't seem to be any obvious documentation on the change (aside from this issue).

Is fixing this a matter of changing the remote on the local repo?

(Wasn't sure whether to create a new issue vs. commenting on this closed issue - let me know which is preferable and I'll adjust)

**Comment by adidalal** [comment]
@joshka Yeah, I think usage has been pretty low, anyway.

To fix, untap and `brew tap alehouse/homebrew-unofficial`

**Comment by joshka** [comment]
@adidalal Thanks :) I can't actually recall why I had it tapped - possibly I was working on a cask I thought belonged there at some point, but realized it was already in versions.

**Comment by megraf** [comment]
@joshka - You can untap the deprecated unofficial by doing: 

`brew untap caskroom/unofficial`
