### ISSUE TITLE
Tracking Java 1.9 Cask updates

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#38574]
Java 1.9 is scheduled for release 21.9.2017 

- [x] Update `java` to 1.9 - https://github.com/caskroom/homebrew-cask/pull/38829
- [x] Update `java-jdk-javadoc` to 1.9 - https://github.com/caskroom/homebrew-cask/pull/38830
____

- [x] Update `java caveats` DSL - https://github.com/Homebrew/brew/pull/3198
___
- [x] Remove `jce-unlimited-strength-policy` - https://github.com/caskroom/homebrew-cask/pull/38807
- [x] Migrate `jce-unlimited-strength-policy` to `versions` - https://github.com/caskroom/homebrew-versions/pull/4485
_____

- [x] Migrate Java 1.8 to `versions` - https://github.com/caskroom/homebrew-versions/pull/4468
- [x] Remove `java-beta` - https://github.com/caskroom/homebrew-versions/pull/4492

**Comment by wenerme** [comment]
Sit and waiting.

**Comment by douglarek** [comment]
It is cool !
