### ISSUE TITLE
Hacktoberfest is back!

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#39060]
# Hacktoberfest is back!

It's that time of the year again, and we are excited to once again participate in Hacktoberfest!

If you've never made a Pull Request before, Homebrew Cask is a great place to start! We provide an easy way to manage GUI apps on macOS.

Help us add and update Casks, or implement new features and iron out bugs over at http://github.com/Homebrew/brew.

We appreciate every contribution, but here's a list of some open issues you could help us out with:

### Casks

Any Cask Request with the [hacktoberfest](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aopen+label%3Ahacktoberfest+label%3A%22cask+request%22) label.

### Features & Bugs

- [ ] [Allow GUI un/installs.](https://github.com/caskroom/homebrew-cask/issues/24377)
- [ ] [Incorporate `name` stanza into `brew cask search`.](https://github.com/caskroom/homebrew-cask/issues/17323)
- [ ] [Some non-existing stanzas do not error out with `_stanza`.](https://github.com/caskroom/homebrew-cask/issues/29289)
- [x] [~~Can we make HB flags not interfere with `cask`?~~](https://github.com/caskroom/homebrew-cask/issues/28977)
- [ ] [`audit`: check availability of URLs and HTTPS versions. ](https://github.com/caskroom/homebrew-cask/issues/25403)
- [x] [~~Allow only a single `uninstall` and `zap` stanza.~~](https://github.com/caskroom/homebrew-cask/issues/23885)

**Comment by reitermarkus** [comment]
Yep, feel free.

**Comment by commitay** [comment]
🎉  List updated.

**Comment by commitay** [comment]
Added https://github.com/caskroom/homebrew-cask/issues/25388 to the list.

**Comment by commitay** [comment]
Hacktoberfest has come to an end, thank you to all contributors who updated Casks or implemented new features / bug fixes!
