### ISSUE TITLE
Draft Roadmap: `brew cask upgrade`

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#4678]
## Explanation

`brew cask upgrade` is frequently brought up on IRC, and there have been a few different issues and PRs where it is discussed (long-running: #309).

`brew cask upgrade` is a high priority to me.  Homebrew-cask is not really a package manager without `upgrade`.  It is also important that when we do ship an `upgrade` verb, it actually works.

There are many prerequisites for our infrastructure to support a `brew cask upgrade` that works reliably, and a few things that should come along with it.

For the benefit of our users, and anyone who wants to participate in coding, here is a general roadmap that shows what some of us have been working on, and where we can go over upcoming months.  I plan to edit this comment in-place over time.

Why is so much attention paid to tokens and versioning?  Because Homebrew-cask uses a simple filesystem-as-a-datastore approach in which Cask tokens and version numbers are used as directory names.  We need to standardize tokens and versions so that files are stored in a predictable place on disk — and because there is no facility to handle renames sensibly.

This is only a draft. It is possible that there is disagreement among the maintainers about certain items.

## Current Implementation

Homebrew-cask is very good at installing, inconsistent on uninstalling, and mostly-incapable on upgrading.  Part of upgrading is implicit uninstalling, so `uninstall` must be made to work equally well as `install` does.

## Roadmap

- [ ] Standardize Cask tokens in repos (2090/2467)
    - [x] Standardize tokens for app Casks (1312)
    - [x] Standardize tokens for font Casks (778)
    - [ ] Standardize tokens for Casks in `homebrew-versions` (102)
    - [ ] Standardize tokens for pkg Casks (179)
    - [ ] Standardize tokens for prefpane Casks (24)
    - [ ] Standardize tokens for qlplugin Casks (22)
    - [ ] Standardize tokens for manual-installer Casks (13)
    - [ ] Standardize tokens for binary-only Casks (10)
    - [ ] Standardize tokens for Casks in `homebrew-unofficial` (8)
    - [ ] Standardize tokens for colorpicker Casks (6)
    - [ ] Standardize tokens for screen-saver Casks (6)
    - [x] ~~Standardize tokens for widget Casks (3, unimportant because they don't work)~~ (support for widgets has been removed as of #8751)
    - [ ] Standardize tokens for service Casks (2)
    - [ ] Standardize tokens for input-method Casks (1)
    - [ ] Standardize tokens for none-of-the-above Casks (1, `adobe-air.rb`)
- [ ] Standardize Cask version numbers in repos (778/2467)
    - [ ] Standardize version numbers for app Casks (1312)
    - [x] Standardize version numbers for font Casks (778)
    - [ ] Standardize tokens for Casks in `homebrew-versions` (102)
    - [ ] Standardize version numbers for pkg Casks (179)
    - [ ] Standardize version numbers for prefpane Casks (24)
    - [ ] Standardize version numbers for qlplugin Casks (22)
    - [ ] Standardize version numbers for manual-installer Casks (13)
    - [ ] Standardize version numbers for binary-only Casks (10)
    - [ ] Standardize tokens for Casks in `homebrew-unofficial` (8)
    - [ ] Standardize version numbers for colorpicker Casks (6)
    - [ ] Standardize version numbers for screen-saver Casks (6)
    - [ ] ~~Standardize version numbers for widget Casks (3, unimportant because they don't work)~~ Support for widgets removed as of #8751 
    - [ ] Standardize version numbers for service Casks (2)
    - [ ] Standardize version numbers for input-method Casks (1)
    - [ ] Standardize version numbers for none-of-the-above Casks (1, `adobe-air.rb`)
- [ ] Algorithmic token-generation and versioning
    - [x] formalize token generation (#2659, #3175, #3255,  #3285, #3305, #3344)
    - [x] write `generate_cask_token` script to generate tokens (#3443)
    - [x] real-world testing period for `generate_cask_token` script
    - [ ] roll current `generate_cask_token` script logic into `brew cask create`
    - [ ] add version-number determination to `generate_cask_token`
        - proposal: for app bundles, pull the version number from `Info.plist`
    - [ ] add version-number determination to `brew cask create`
- [ ] All pkg-based Casks must have `uninstall` stanzas
    - [x] complete tracking issue at #3322 (almost finished, thanks to @alebcay)
    - [ ] add a `brew cask audit` test to keep out any new entries without `uninstall`
- [x] Make the `uninstall` stanza available to all Cask types
- [x] Nail down changes to the DSL
    - it will always be possible to add to the DSL, but it will become more difficult to remove from the DSL
    - [x] remove `md5` stanza (#2931)
    - [x] remove `sha1` stanza (#4264)
    - [x] remove `no_checksum` stanza (#4689)
    - [x] tracking issue for further DSL changes (#4688)
- [ ] Use appcasts to detect updates
    - [x] add `appcast` stanza to DSL (#3105)
    - [x] snapshot appcast content and wait several weeks for real-world comparisons (was done for ~200 Casks on 3 March)
    - [x] find standard Sparkle-based appcast URLs for all app Casks (#4412, #4646, #4648, #4674, #4780, #4783, #4829)
    - [ ] find non-standard/non-Sparkle appcast URLs for all other self-updating apps (eg GitHub.app)
        - [ ] recently-added `link` Casks
        - [ ] non-`link` Casks
        - [ ] Casks that use Sparkle with small modifications (check for Sparkle.Framework inside the App bundle)
        - [ ] Casks that use Sparkle with `SUFeedURL` set to `SET_PROGRAMMATICALLY_BY_APPLICATION_HELPER`
        - [ ] Casks that use non-Sparkle appcasting
        - [ ] Casks that had `Info.plist` in unexpected location
    - [x] extend appcast stanza to support sha256 hashes
    - [ ] store expected appcast hashes inline with Casks
    - [ ] ability to show appcast status in `brew cask list`
    - [ ] generate automatic notifications to maintainers on appcast update
    - [ ] start checking incoming Casks for appcasts routinely
        - without imposing load on Cask authors
        - `brew cask create` could do this if it is pointed at an app bundle
- [ ] Migrate as many `'latest'`-scheme Casks to version numbers as possible
    - prediction: we will never be able to entirely remove the `'latest'` scheme
    - [ ] migrate to versioned download URLs revealed by appcasts
    - [ ] migrate to versioned download URLs revealed by HTTP redirects
    - [ ] migrate to versioned download URLs revealed by metadata? 
        - [x] new devscript to support this: `list_url_attributes_on_file`
- [ ] Support for a `~/.brewcaskconfig` file
    - git-style format
    - bundle a license-compatible library as was done for the [plist parser](https://github.com/caskroom/homebrew-cask/blob/master/lib/plist/parser.rb), or roll our own
    - the CLI should be able to write to the config file as with git
    - support for environment variables should be REMOVED
- [ ] Bookkeeping: keep records of what was done at install-time, as in #3066
    - [ ] add new command verb to display the install record for a given cask
- [ ] Make `brew cask uninstall` refer to the previously recorded Cask/version, rather than the current repo
- [ ] Expose discrete installation phases with new command verbs
    - [x] `fetch` (#2970)
    - [ ] `stage`
        - part of the reason to separate out staging is to implement `brew cask audit --stage`
    - [ ] `preflight` (fairly unimportant)
    - [ ] `link`
        - ability to re-link already installed Cask
        - ability to un-link Cask without removing it from Caskroom
    - [ ] `postflight`
    - [x] `zap` (new functionality; zap phase not implicit under default `install`)
- [ ] New command verb to dump a shell script which will re-create the existing install
    - desirable feature: option to use stored metadata instead of implicitly upgrading
- [ ] New command verb to rename versioned Caskroom directories to match in-place updates performed independently by apps
- [ ] `brew cask audit --stage`
    - needed if we are going to start depending on `Info.plist`
- [ ] New command verb `outdated` (#9490)
    - consult `Info.plist` as well as versioned directory name
    - leave room for the planned feature of managing multiple installed versions
- [ ] Ability to remove currently-installed, but outdated (unlinked) versions.
    - interface could be through `brew cask cleanup` as suggested in #4651
- [ ] New command verb `upgrade`
- [ ] Update `HACKING.md` re: upgrade verb

**Comment by ponychicken** [comment]
What is meant by standardize app names? If that involves going through the cask and formatting the name tag is some specific kind of way, than this would be something I could help at.

**Comment by rolandwalker** [comment]
@ponychicken help would be welcome, though this checklist was out-of-sync with current terminology.

The `name` stanza doesn't affect upgrading, while the Cask token (filename, essentially) does affect it.

I've updated the text above to clarify.

**Comment by NathanJang** [comment]
Meanwhile I've been running

```bash
brew update
brew cask list | xargs brew cask install
```

which of course shows warnings for apps that don't have upgrades available. However, cask will download and install updates without deleting the old version, so I've had to manually delete the old versions. This is a dirty hack, so I'll be expecting problems with this in the future. None so far though.

**Comment by c00kiemon5ter** [comment]
I've written a script to upgrade cask packages. 
It is written in POSIX sh and can be found [on this gist](https://gist.github.com/c00kiemon5ter/3730069b6c920841a3ca)

Some packages do not have a common version string - just `latest`.
In such case one needs to pass `-l` to forcefully upgrade all such packages. 
There is also a verbose `-v` mode, to output more detailed version information. 

Have fun o/

**Comment by blogabe** [comment]
I believe this is the quickest simplest command to upgrade the brew cask packages:
`for c in ``brew cask list``; do ! brew cask info $c | grep -qF "Not installed" || brew cask install $c; done`

I believe I got the command from another thread discussing this topic as I am not the original author.

This will upgrade all versioned, read, not "latest", casks.  The "latest" casks can get upgraded directly through the program.

Similarly to @NathanJang I have to delete the older casks after upgrading.

**Comment by NathanJang** [comment]
Now that I think about it, `brew` itself [does not remove old versions](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-uninstall-old-versions-of-a-formula). Perhaps it would be useful to write a separate `brew-cask-cleanup` to do that.

**Comment by schwa** [comment]
Any progress expected to be made here?

**Comment by vitorgalvao** [comment]
@schwa There is progress made; look at all the checkmarks. Everything unchecked still needs to be done, and any help is appreciated.

**Comment by orangeudav** [comment]
My [gist](https://gist.github.com/orangeudav/26a8752ae54a169b8516) for cleaning old versions.

**Comment by neurogenesis** [comment]
Regarding the syntax debate of ```brew cask update && brew cask upgrade``` vs. ```brew update && brew upgrade```, it's great to see the features for this work consolidated into a single issue. If the syntax hasn't already been decided, I thought I'd summarize what I've read up to now and offer a different perspective from "one or the other, exclusively":

*Both notations should be supported, as if it were a plugin*...
  * I should be able to update only those packages that are managed by cask, or any other subset of the homebrew ecosystem.
  * I should be able to update everything installed via the homebrew ecosystem with a single command ```brew upgrade``` (which should also inherently run update to grab latest metadata, as bundle / berks and other tools do).

1. The rationale against ```brew upgrade```, in favor of ```brew cask upgrade```:
  1. cask is a separate project and maintained independently from homebrew
    - NOTE: it's not so separate that we invoke cask directly vs. a subcommand of brew
  1. if i install it with ```brew cask install [pkg]```, i should upgrade it with ```brew cask upgrade [pkg]```
  1. having both ```brew ...``` AND ```brew cask ...``` is too confusing for users
    - NOTE: i don't buy it, i use the CLI because i want options and finer control

1. The rationale against ```brew cask upgrade```, in favor of ```brew upgrade```:
  1. while a separate project, it is closely integrated with homebrew itself
  1. if other tools like cask existed, it's a usability improvement to simply run ```brew upgrade``` instead of ```brew upgrade && brew cask upgrade && brew fonts upgrade && ...```

If it's possible that cask-like extensions to homebrew might pop up as well, and we want homebrew to rule them all, then syntax and behavior of each of the tools should be consistent with the main project and its derivatives. To make this easier, thinking of cask as a plugin framework for homebrew might be the best option. I acknowledge that cask isn't written as a plugin, but it helps to think of it that way to envision how the overall ecosystem could/should work.

To take the plugin idea further, some examples of this might be a font manager ```brew fonts ...``` and a CLI interface to upgrade AppStore apps ```brew appstore```. So now I have 4 different related tools to manage all my packages for OS X:

- ```brew search | install | uninstall | list | update | upgrade ...```
- ```brew cask search | install | uninstall | list | update | upgrade | outdated ...```
- ```brew fonts search | install | uninstall | list | upgrade | outdated ...```
- ```brew appstore search | install | uninstall | list | upgrade | outdated ...```

Each will need a method of installing, listing, updating metadata and upgrading packages. Each may implement them differently, but they should share similar syntax. If each of those subcommands are implemented as hooks, then integrating them back into the parent homebrew project should be easier. Doing so would help projects integrate cleanly with homebrew and would simplify upgrading everything from a single command: ```brew upgrade```. This is to say that brew upgrade would invoke the hooks for each installed plugin.

This would allow for either: ```brew upgrade``` or ```brew cask upgrade```, where the former includes the latter and the latter would update all casks but not ```brew fonts upgrade``` or ```brew appstore upgrade```. It gives the user the option of upgrading everything or by subgroup.

While significant changes would be required from homebrew for that to work properly, cask can and should support both syntaxes with the greater usability in mind.

**Comment by alebcay** [comment]
> If it's possible that cask-like extensions to homebrew might pop up as well, and we want homebrew to rule them all, then syntax and behavior of each of the tools should be consistent with the main project and its derivatives. To make this easier, thinking of cask as a plugin framework for homebrew might be the best option. I acknowledge that cask isn't written as a plugin, but it helps to think of it that way to envision how the overall ecosystem could/should work.

I certainly like the idea of a plugin-based paradigm. Specifically, I like the idea of hooks for updating and upgrading.

That being said, I would take this up with the people up at Homebrew. If they _were_ to introduce a plugin system of sorts (they are starting to move in that direction, with the new transparent update system), I would expect a considerable amount of support for Cask (and other similar Homebrew subprojects) to move in that direction. But at the end of the day, Cask exists to "provide a friendly homebrew-style CLI workflow for the administration of Mac applications distributed as binaries." Writing a plugin interface to achieve that simply seems like overkill for the time being.

I think a plugin system is probably big enough to justify its own project if the people upstream decide not to do it.

**Comment by leipert** [comment]
If your a user of maid [benjaminoakes/maid](https://github.com/benjaminoakes/maid), you could using this [gist](https://gist.github.com/leipert/8a2b2d5bc6154e8ec135). Thanks @orangeudav and @blogabe for the inspiration.

**Comment by rolandwalker** [comment]
The DSL changes all got done, but I am no longer working on this roadmap.

**Comment by leipert** [comment]
Wait. Does this mean there will be no brew cask upgrade in the foreseeable future?

**Comment by vitorgalvao** [comment]
There are plans (that need a bit more discussion and an official announcement I’ll need to write up) to change homebrew-cask’s behaviour from linking to copying (long story short, linking sucks for GUI apps are we’re just building workarounds on top of workarounds, making it an incredibly broken model), so `upgrade` (which was moving slowly anyway) will have to be revised anyway.

**Comment by szhu** [comment]
Good to hear that links are going away! Can you link to gh issues surrounding this change?

**Comment by vitorgalvao** [comment]
There are none yet, @szhu. But don’t worry [I didn’t forget about you](https://github.com/caskroom/homebrew-cask/issues/3083). At the moment this is just an idea that hopefully will be discussed and set in march soon. I strongly believe it’s the right one, though.

**Comment by szhu** [comment]
I actually forgot that I wrote that, thanks :)

**Comment by tjnycum** [comment]
> There are plans (that need a bit more discussion and an official announcement I’ll need to write up) to change homebrew-cask’s behaviour from linking to copying (long story short, linking sucks for GUI apps and we’re just building workarounds on top of workarounds, making it an incredibly broken model), so upgrade (which was moving slowly anyway) will have to be revised anyway.
Is the discussion (that's taken place so far) about linking vs. copying documented anywhere?

**Comment by tjnycum** [comment]
>There are plans (that need a bit more discussion and an official announcement I’ll need to write up) to change homebrew-cask’s behaviour from linking to copying (long story short, linking sucks for GUI apps and we’re just building workarounds on top of workarounds, making it an incredibly broken model), so upgrade (which was moving slowly anyway) will have to be revised anyway.

>At the moment this is just an idea that hopefully will be discussed and set in march soon. I strongly believe it’s the right one, though.

*Please* wait for open discussion of that before you make up your mind. I'm under no illusion that there's a perfect solution—each option has its strengths and weaknesses—but I find the idea that requiring everyone to keep two copies of every app they install via cask is the best course of action *very* difficult to swallow.

**Comment by vitorgalvao** [comment]
Plans will be posted soon (should be today or tomorrow). No one is talking about keeping two copies, though, “copy” is a reference to how we referred to the feature in the past, it doesn’t mean duplicating stuff (actually, we’ll take less space in some cases).

Linking has shown to be a bad subpar solution for this, so keeping that is not an option. For homebrew-cask to evolve in other areas, we need this change: it’ll solve a bunch of issues right of the bat. Will it introduce new ones? We’ll have see how it evolves.

I’ll go into all the reasoning at length in the announcement, though (it’ll be a regular github issue). Please also don’t think there hasn’t been open discussion on this — there has (like the issue I linked to before). A big part of the reasoning to do it the current way has been [ideological](https://github.com/caskroom/homebrew-cask/issues/3083#issuecomment-35802432) but that approach isn’t working.

[The goal of homebrew-cask isn’t changing](https://github.com/caskroom/homebrew-cask/issues/12775#issuecomment-124273149), though, but it is time to try a different solution.

**Comment by salimane** [comment]
+1

**Comment by vitorgalvao** [comment]
@salimane Please stop spamming issues. This is closed, don’t `+1` it, or any other issue, for that matter, it won’t make issues get worked on faster (or at all).

**Comment by salimane** [comment]
@victorpopkov you're right, this was closed :)

**Comment by kristian-hermansen** [comment]
So what is the actual solution???

**Comment by chilloutman** [comment]
Here's a workaround that mostly works:

`brew cask list | xargs brew cask install`

I'm pretty sure a propper solution is WIP.

**Comment by 9Yg1rxeSeha90ZU1** [comment]
for app in $(brew cask list); do cver="$(brew cask info "${app}" | head -n 1 | cut -d " " -f 2)"; ivers=$(ls -1 "/opt/homebrew-cask/Caskroom/${app}/.metadata/" | tr '\n' ' ' | sed -e 's/ $//'); aivers=(${ivers}); nvers=$(echo ${#aivers[@]}); echo "[*] Found ${app} in cask list. Latest available version is ${cver}. You have installed version(s): ${ivers}"; if [[ ${nvers} -eq 1 ]]; then echo "${ivers}" | grep -q "^${cver}$" && { echo "[*] Latest version already installed :) Skipping changes ..."; continue; }; fi; echo "[+] Fixing from ${ivers} to ${cver} ..."; brew cask uninstall "${app}" --force; brew cask install "${app}"; done

**Comment by tonyseek** [comment]
My adhoc solution: https://gist.github.com/tonyseek/afa5902eb2713ca6cfab

**Comment by 9Yg1rxeSeha90ZU1** [comment]
@tonyseek yeah i had implemented a hack one-liner above very similar to your with exception of default path not being checked ;)

**Comment by orangeudav** [comment]
Simple cleaning based on ctime https://gist.github.com/orangeudav/29a58c8df6446a87c50ec035b2b5dfcd

**Comment by RandomDSdevel** [comment]
@orangeudav:  What does your scripted alternative to `brew cask cleanup` have to do with this thread, where we're discussing ways to make up for Homebrew Cask's lack of a _`brew cask upgrade`_ command?

**Comment by 9Yg1rxeSeha90ZU1** [comment]
Does not my little hack work for you?

https://gist.githubusercontent.com/9Yg1rxeSeha90ZU1/7d66cf35bae4c8d251bfd4185575a80b/raw/1e9fde8caba83fb18578ea859f0a10270ebc1b0b/brew.cask.upgrade.sh

**Comment by vitorgalvao** [comment]
This is a closed issue. There are a bunch of workarounds posted by people. No more are needed. What we need is a native solution.

Please stop spamming our inboxes with the same broken alternatives. Locking.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/29301
