### ISSUE TITLE
Separate the Ruby backend from internal Homebrew dependencies

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#5080]
## Background

Homebrew-cask is implemented as a Homebrew external command, in the form of
`brew-cask.rb`, which is `require`d by the `brew` command.  This means that
Homebrew-cask has full access to, and is constrained by, the Ruby runtime
provided by Homebrew.

Initially it was thought that Homebrew-cask would re-use much of Homebrew's
code internally.  That turned out not to be the case in practice, largely
because Homebrew's code is organized around the Formula.

## Proposal

`brew-cask.rb` should be re-implemented as an executable `brew-cask`, which
would be **invoked** by Homebrew rather than `require`d.  `brew-cask` would
then execute completely independently of Homebrew's Ruby environment.

This would be an internal-only change.  The user interface would stay the
same.  Commands would still be invoked via `brew cask <verb>`, and we would
still piggyback on `brew update` to get new Casks.

## Advantages

 - **Stability**.  Homebrew does not guarantee any internal APIs.
   Homebrew-cask frequently breaks due to changes within Homebrew
  (#4732,  #4982, #4229, many others).

- **Clarity**.  Where we do re-use Homebrew's classes (such as for
  downloading), we do so only partially, with some methods overridden.
  This needlessly obscures what the code is doing, making it more difficult
  to diagnose bugs or develop new functionality.

- **Error Reporting**.  Both Homebrew and Homebrew-cask attempt to
   rescue exceptions and direct users to the relevant issues URL.  @voanhduy1512
   did some good work on this problem, but it still crops up as in #5108.  Every
   misdirected report is a drain on maintainers (in both projects).

- **Cleanup**. Currently `brew cask cleanup` works in a roundabout
  way (using tracking symlinks) because we share a download location
  with Homebrew.  It would be more robust to maintain our own download
  cache.

- **Ruby 2.0**.  We would have the choice to be more aggressive about
  switching to Ruby 2.0 (say, 6 months after Yosemite is released).  We
  could require Mountain Lion and earlier to install Ruby 2.0 as a
  prerequisite.  This would not only gain us access to new language
  features, but reduce the currently-imposed burden of maintaining
  compatibility across Ruby 1.8 and 2.0.

- **Freedom**.  Currently we are constrained by Homebrew's decisions with
  regard to character encodings, interpreter version, monkeypatching -- all
  things that, once inherited, we cannot easily undo.

## Disadvantages

 - **Tap Migration**. We have sometimes used internal interfaces to Homebrew
    which are not available externally, as with the tap migration code (#4169).
    However, this also could have been accomplished by copying the relevant
    logic from Homebrew.

- **Integration for files in /usr/local**.  Some Casks install files into `/usr/local`,
    which causes `brew doctor` to complain as in #2350 and others.  Currently
    we have a `caveats` warning for this, which is not really a fix.  As mentioned
    in #3693, we could fully resolve the problem by installing files to a Homebrew
    Cellar, and then symlinking into the Cellar as with any other Homebrew
    installation.  Such a technique would become more difficult if we could not
    call directly into Homebrew.
    - However, it also seems that nobody is working on that implementation.
    - There are other possible approaches, such as generating an *ad hoc* Formula.

## Places where we currently re-use Homebrew's code (incomplete)

 - global methods such as `onoe` (example [install.rb](https://github.com/caskroom/homebrew-cask/blob/300b563b73cb76a2cfa68ba097c3aadd57d52b80/lib/cask/cli/install.rb#L26))
     - these are mostly trivial
     - relevant code would have to be forked from Homebrew
     - in some cases, we can simplify and/or get more desirable behavior
 - monkeypatched methods on Pathname ?
     - preferable to remove these where they may exist
     - we at least use our own variant monkeypatch `cabv` (#2991)
 - implicit tapping (#2303)
     - can be replaced by invoking `brew tap <Tapname>`
 - downloading, eg `Cask::CurlDownloadStrategy` (see comments in [download_strategy.rb](https://github.com/caskroom/homebrew-cask/blob/23c930f68d7f1eea0718814f5f4a0a4654ee9bfc/lib/cask/download_strategy.rb#L3))
     - relevant code would have to be forked from Homebrew
 - calculation of checksums
     - would be simplified, as our project only uses one checksum type
 - `depends_on_formula` (#2305)
     - can be replaced by invoking `brew install <formula>`
 - automatic tap migration (#4169)
     - this code was meant to be temporary in any case
 - test suite
     - we have also been discussing rearchitecting the test suite to use RSpec

## Tracker

 - [x] Wait until Tap migration code can be safely removed (minimum of 90 days,
       roughly 3 August.)
 - [x] Convert `brew-cask.rb` to a bash-script executable shim `brew-cask` (#8089)
 - [x] Update Formula `brew-cask.rb` (a different file) to support the new setup (#8089)
 - [x] Fork and check in all Homebrew code needed for tests to pass (#8089)
 - [ ] Refactor: integrate all needed classes & methods organically in our codebase
     - [x] #8155
     - [x] #8158
     - [x] #8188
     - [x] #8189
     - [x] #8194
     - [x] #8195
     - [x] #8196
     - [x] #8197
     - [x] #8218
     - [x] #8221
     - [x] #8225
     - [x] #8226
     - [x] #8227
     - [x] #8228
     - [x] #8229
     - [x] #8230
     - [x] #8247
     - [x] #8261
     - [x] #8263
     - [x] #8264
     - [x] #8265
     - [x] #8266
     - [x] #8268
     - [x] #8295
     - [x] #8296
     - [x] #8297
     - [x] #8298
     - [x] #8308
     - [x] #8310
     - [x] #8312
     - [x] #8314
     - [x] #8328
     - [x] #8329
     - [x] #8330
     - [x] #8331
     - [x] #8332
     - [x] #8333
     - [x] #8334
     - [x] #8335
     - [x] #8336
     - [x] #8337
     - [x] #8338
     - [x] #8339
     - [x] #8340
     - [x] #8341
     - [x] #8342
     - [x] #8361
     - [x] #8369
     - [x] #8388
     - [x] #8389
     - [x] #8390
     - [x] #8391
     - [x] #8392
     - [x] #8393
     - [x] #8402
     - [x] #8403
     - [x] #8425
     - [x] #8426
     - [x] #8427
     - [x] #8428
     - [x] #8433
     - [x] #8434
     - [x] #8435
     - [x] #8436
     - [x] #8437
     - [x] #8446
     - [x] #8447
     - [x] #8448
     - [x] #8458
     - [x] #8460
     - [x] #8461
     - [x] #8464
     - [x] #8466
     - [x] #8522
     - [x] #8539
     - [x] #8552
     - [x] #8556
     - [x] #8557
     - [x] #8559
     - [x] #8561
     - [x] #8595
     - [x] #8611
     - [x] #8612
     - [x] #8721
     - [x] #8724
     - [x] #8870
     - [ ] make `Hbc::SystemCommand` safe for commands with large writes to STDERR as performed by curl
     - [ ] execute curl via `Hbc::SystemCommand`, migrating it out of homebrew-fork
     - [ ] migrate `Hbc::HbCurlDownloadStrategy` from homebrew-fork
     - [ ] `Hbc::HbSubversionDownloadStrategy` cleanups
         - [ ] remove `shell_quote` method
         - [ ] use `Hbc::SystemCommand` instead of `quiet_system`
         - [ ] use `Hbc::SystemCommand` instead of backticks
     - [ ] migrate `Hbc::HbSubversionDownloadStrategy` from homebrew-fork
     - [ ] migrate `Hbc::HbVCSDownloadStrategy` from homebrew-fork
     - [ ] revise download caching
         - [ ] create our own cache at `/Library/Caches/Homebrew-cask`, setting value in `Hbc::Locations`
         - [ ] remove `HOMEBREW_CACHE` constant from `global.rb`
         - [ ] remove `HOMEBREW_CACHE` constant from `testing_env.rb`, and inject a test value for both rspec and minitest
         - [ ] transitional code: at startup, automatically purge *all* old files tracked by `/Library/Caches/Homebrew/Casks`, if seen
         - [ ] simplify `brew cask cleanup` (no longer needs to use subdirectory and tracking symlinks)
     - [ ] delete homebrew-fork `download_strategy.rb`
     - [ ] delete homebrew-fork `exceptions.rb`
     - [ ] delete homebrew-fork `global.rb`
     - [ ] delete homebrew-fork `monkeypatch_pathname.rb`
     - [ ] delete homebrew-fork `testing_env.rb`
     - [ ] delete homebrew-fork `utils.rb`
 - [ ] delete directory `lib/vendor/homebrew-fork`

Edits:
 - added Disadvantage / Integration for files in `/usr/local`
 - added Tracker
 - added Error Reporting
 - renamed Plan to Tracker; filled out Tracker details

**Comment by vitorgalvao** [comment]
@jawshooah Since we now want to go in the opposite direction, should we close this, or is it still useful in some way?

**Comment by jawshooah** [comment]
No use in leaving it open.

**Comment by jawshooah** [comment]
No use in leaving it open.
