### ISSUE TITLE
Draft Roadmap: Cask DSL 1.1

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#5586]
This comment was accidentally overwritten at one point, and needs to be expanded.

- [x] make the `name` stanza mandatory
- [ ] accept special value `:unknown` for most stanzas
- [ ] glob/expand
- [ ] `plist_add` (analogous to `plist_set`)
- [ ] `defaults_set` (analogous to `plist_set`)
- [ ] make postflight methods available in all similar blocks (currently some are, but not documented)
- [ ] suppress methods which should not be exposed within `postflight`
- [x] closed-source license variations (or remove unsupported code) (#8129, #8090)
- [ ] extended support for CLI-only Unixish distributions
