### ISSUE TITLE
List of all per-Cask todo comments

### ISSUE THREAD

**Issue by iggyvolz** [caskroom/homebrew-cask#8202]
Below is a list of all todos inside of Homebrew Cask, sorted by todo name and file.  For those curious, here's how I generated it: https://gist.github.com/iggyvolz/93f17a54ad2e22077fc0

"Improve this machine-generated value" has thousands of uses so it is simply the number that is listed.
[`bittorrent-sync.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/bittorrent-sync.rb)

- [x] "response was not XML" in [`bittorrent-sync.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/bittorrent-sync.rb#L6)
- [ ] "glob/expand needed here" in [`clamxav.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/clamxav.rb#L20)
- [x] "the URL indicates there is an appcast" in [`colorpicker-propicker.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/colorpicker-propicker.rb#L5)
- [ ] "the nested_container hack must be revised when container :nested stops being an alias around 0.50.0" in [`decitime.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/decitime.rb#L15)
- [x] "should this be" in [`dwarf-fortress.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/dwarf-fortress.rb#L9)
- [ ] "verify that this does not contain user-generate content" in [`filezilla.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/filezilla.rb#L10)
- [ ] "is this user-created content?" in [`fontexplorer-x-pro.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/fontexplorer-x-pro.rb#L12)
- [ ] "This is a horrible hack […]. The backend code should be fixed" in [`git-annex.rb`](../blob/1d60a07c4bdf8ea54659ccd553090964ea1ef857/Casks/git-annex.rb#L8-L9)
- [ ] "remove all ENV variables" in [`gpgtools.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/gpgtools.rb#L12)
- [ ] "an uninstall stanza should be provided, and this message removed" in [`hear.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/hear.rb#L13)
- [ ] "expand/glob for '~/Library/<userid>/HipChat/'," in [`hipchat.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/hipchat.rb#L17)
- [x] "what is the reason for this?" in [`jabber-video.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/jabber-video.rb#L11)
- [x] "(none provided)" in [`ksdiff.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/ksdiff.rb#L12)
- [x] "unsure if these contain user-created content" in [`launchbar.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/launchbar.rb#L22)
- [x] "is "uninstal" below (one "l") a typo" in [`mcs783x.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/mcs783x.rb#L17)
- [x] "verify that this does not contain user-created content" in [`ngrok.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/ngrok.rb#L11)
- [ ] "these will not work because the glob will not be expanded" in [`programmer-dvorak.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/programmer-dvorak.rb#L14)
- [ ] "verify that this does not contain user-generated content" in [`soulver.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/soulver.rb#L17)
- [ ] "glob/expand support" in [`soulver.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/soulver.rb#L21)
- [x] "mistaken capital A in .app name?" in [`time-sink.rb`](../blob/db9b3de003b20a4489d3c73700ff0e468c7dbc02/Casks/time-sink.rb#L9)

**Comment by jpodlech** [comment]
@iggyvolz , regarding Jabber Video, I've added the `rm` command in order cleanup the configuration. The reason behind this is that this version of Jabber is locked to http://collaboration.iu.edu students and this is the only way we can unlock it. I'm open to suggestions. Sorry for delay on my response.

**Comment by adityadalal924** [comment]
Re: ngrok - ngrok now creates a  ~/.ngrok2 directory with an `ngrok.yml` inside. This is strictly a configuration file (examples [here](https://ngrok.com/docs#config-examples)), and should be removed with a zap, but not necessarily an uninstall.

I can put in a pull request to update the formula if deemed appropriate.

**Comment by vitorgalvao** [comment]
Please do, @adityadalal924.

**Comment by vitorgalvao** [comment]
This was a great effort, but now most of these are the same (glob related), and some have been fixed and others added without touching the list, so closing as we have open issues for the big pictures.
